[build]
  command = "npm ci && npm run test:ci && npm run build"
  publish = "dist/portfolio/browser"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_SKIP_ANGULAR_RUNTIME = "true"
  CHROMEDRIVER_SKIP_DOWNLOAD = "true"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "true"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  DISPLAY = ":99"

[[plugins]]
  package = "netlify-plugin-chrome"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false