[build]
  command = "npm ci && npm run build:prod"
  publish = "dist/portfolio/browser"

[build.environment]
  NODE_VERSION = "22"
  NETLIFY_SKIP_ANGULAR_RUNTIME = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false